// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import(
	"time"
)

const TableNameTbTAccount = "user_information"

// TbTAccount mapped from table <tb_t_account>
type TbTAccount struct {
    ID           int32     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
    Name         string    `gorm:"column:name;type:varchar(50);not null" json:"name"`
    Username     string    `gorm:"column:username;type:varchar(50);not null" json:"username"`
    Email        string    `gorm:"column:email;type:varchar(50);not null" json:"email"`
    Password     string    `gorm:"column:password;type:varchar(225);not null" json:"password"`
    AccessToken  string    `gorm:"column:access_token;type:varchar(512)" json:"access_token"`
    RefreshToken string    `gorm:"column:refresh_token;type:varchar(512)" json:"refresh_token"`
    CreatedAt    time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
    UpdatedAt    time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TbTAccount's table name
func (*TbTAccount) TableName() string {
	return TableNameTbTAccount
}
